repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: check-json
    exclude: (settings|launch|extensions).json
  - id: check-shebang-scripts-are-executable
  # - id: detect-aws-credentials
  - id: detect-private-key
  - id: trailing-whitespace
# - repo: https://github.com/aws-cloudformation/cfn-python-lint
#   rev: v0.61.0
#   hooks:
#   - id: cfn-python-lint
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.4.0
  hooks:
  - id: editorconfig-checker
    alias: ec
    files: .editorconfig
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ['--config=setup.cfg']
    types: [python]
    additional_dependencies:
      - flake8
      - flake8-black
      - flake8-isort
      - isort
      - black
    language_version: python3
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.4
  hooks:
  - id: shellcheck
